### ISSUE TITLE
minigame error

### ISSUE THREAD

**Issue by alirezaraz21** [OxFF00FF/Hamsters_mayhem#1]
400 | {'error_code': 'DAILY_KEYS_MINI_GAME_CANT_CIPHER_USER_DECODING', 'error_message': 'Cant MiniGame cipher user decoding'}

This error is given for some accounts

**Comment by OxFF00FF** [comment]
i fixed errors. 
for this to work you need to get the token 'Bearer .....' from the browser version of hamster kombat
