### ISSUE TITLE
Счетчик карт для улучшения

### ISSUE THREAD

**Issue by edwardtich1** [OxFF00FF/Hamsters_mayhem#3]
Поскольку в достижениях появились следующие пункты:

- Улучшить карты
- Улучшить карты до уровня 15
- Улучшить карты до уровня 25

Возможно ли добавить счетчик карт? 
Например: 

- общее кол-во карт
- потенциальные ID карт которые нужно обновить для выполнения достижения

**Comment by OxFF00FF** [comment]
Можно,  но зачем,  если можно посмотреть это в аккаунте

**Comment by edwardtich1** [comment]
Вопросов больше не имею)
